services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    restart: unless-stopped
    ports:
      - "8281:8080"
    volumes:
      - /data/termix:/app/data
    environment:
      PORT: "8080"

volumes:
  termix-data:
    driver: local
